access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/civicapp
    username: root
    password: 332003
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
# Logging level

# GitHub

# Google




server:
  port: 8081
logging:
  level:
    org.springframework.security: DEBUG

